---
title: "STAT 380 Fianl Project"
output: html_notebook
author: Nicholas Anderson
---

```{r}
library(tidyverse)
library(sf)
library(mapview)
library(dplyr)
library(glmnet)
library(leaps)
library(caret)

set.seed(1)
data <- read.csv("house_data.csv", header = TRUE, sep = ",")
ranData <- sample_n(data, 500) %>% select(-date)
ranData
```

```{r}

#mapview(ranData, xcol = "long", ycol = "lat", crs = 4269, grid = FALSE)
```


```{r}
lr_model_rooms <- lm(price ~ bedrooms + bathrooms, data = ranData)
summary(lr_model_rooms)
```


```{r}
lr_model_size <- lm(price ~ sqft_living + sqft_lot, data = ranData)
summary(lr_model_size)
```

```{r}
lm_price_age <- lm(price ~ yr_built, data = ranData)
summary(lm_price_age)
```

```{r}
regressionDf <- ranData %>%
  select(-id)

regfit.full = regsubsets(price ~ ., data = regressionDf,  nvmax = 18, method="forward")
summary(regfit.full)

reg.summary <- summary(regfit.full)

par(mfrow=c(2,2))

plot(reg.summary$cp ,xlab="Number of Variables ",ylab="Cp", type='l')
min_cp <- which.min(reg.summary$cp )
points(min_cp, reg.summary$cp[min_cp],col="blue",cex=2,pch=20)

plot(reg.summary$bic ,xlab="Number of Variables ",ylab="BIC",type='l')
min_bic <- which.min(reg.summary$bic)
points(min_bic,reg.summary$bic[min_bic],col="blue",cex=2,pch=20)


plot(reg.summary$adjr2 ,xlab="Number of Variables ", ylab="Adjusted RSq",type="l")
max_adjr2 <- which.max(reg.summary$adjr2)
points(max_adjr2,reg.summary$adjr2[max_adjr2], col="blue",cex=2,pch=20)
```

```{r}
avgPriceByYr <- ranData %>% select(price, yr_built, grade) %>%
  group_by(yr_built) %>%
  summarise(avgPrice = mean(price), avgGrade = mean(grade))

avgPriceByYr


```










Source: <https://www.kaggle.com/datasets/abdallahwagih/house-price>
